DEFAULT_TAGS = """
{
  "landuse_tags": [
    "retail"
  ],
  "amenity_tags": [
    "pub",
    "bar",
    "cafe",
    "restaurant",
    "pharmacy",
    "bank",
    "fast_food",
    "food_court",
    "ice_cream",
    "library",
    "ferry_terminal",
    "clinic",
    "doctors",
    "hospital",
    "pharmacy",
    "veterinary",
    "dentist",
    "arts_centre",
    "cinema",
    "community_centre",
    "casino",
    "fountain",
    "nightclub",
    "studio",
    "theatre",
    "dojo",
    "internet_cafe",
    "marketplace",
    "post_opffice",
    "townhall"
  ],
  "shop_tags": [
    "mall",
    "bakery",
    "beverages",
    "butcher",
    "chocolate",
    "coffee",
    "confectionery",
    "deli",
    "frozen_food",
    "greengrocer",
    "healthfood",
    "ice_cream",
    "pasta",
    "pastry",
    "seafood",
    "spices",
    "tea",
    "department_store",
    "supermarket",
    "bag",
    "boutique",
    "clothes",
    "fashion",
    "jewelry",
    "leather",
    "shoes",
    "tailor",
    "watches",
    "chemist",
    "cosmetics",
    "hairdresser",
    "medical_supply",
    "electrical",
    "hardware",
    "electronics",
    "sports",
    "swimming_pool",
    "collector",
    "games",
    "music",
    "books",
    "gift",
    "stationery",
    "ticket",
    "laundry",
    "pet",
    "tobacco",
    "toys"
  ],
  "leisure_tags": [
    "adult_gaming_centre",
    "amusement_arcade",
    "beach_resort",
    "fitness_centre",
    "garden",
    "ice_rink",
    "sports_centre",
    "water_park"
  ]
}
"""

DEFAULT_LOCATIONS = [
    ('', '-- Choose or enter Custom Location --'),
    ('47.226, 8.818', 'Rapperswil'),
    ('47.372, 8.541', 'Zürich'),
    ('47.2404, 8.7233', 'Stäfa'),
    ('45.4647, 9.1911', 'Milano'),

]

DEFAULT_RADIUS = 1000
