version: '3'
services:
  webapp:
    build: ./webapp
    env_file: ./webapp/.env
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=gis
      - FLASK_DEBUG=true
    volumes:
      - ./webapp:/webapp/
      - ./data/:/data/
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  notebooks:
    build: ./notebooks
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=gis
    volumes:
      - ./data/:/data/
      - ./notebooks/notebooks:/home/jovyan/
      - ./test-cases/:/test-cases/
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  postgres:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=
    volumes:
      - ./postgres/storage/:/var/lib/postgresql/data/
      - ./data/alter_config.sh:/docker-entrypoint-initdb.d/alter_postgres_config.sh
    ports:
      - "54320:5432"
